import Foundation

struct ContractEmitter {
    let graph: ContractGraph
    var names: [String: String] = [:]
    var pending: [String] = []

    mutating func emit() throws -> [GeneratedContractFile] {
        let root = try graph.resolved(graph.root)
        _ = try type(root.pointer, suggested: graph.swiftName)
        var files: [GeneratedContractFile] = []
        var index = 0
        while index < pending.count {
            let pointer = pending[index]
            index += 1
            let node = try graph.node(pointer)
            guard let name = names[pointer] else { throw graph.error(pointer, "Missing allocated Swift name") }
            let body: String
            switch node.kind {
            case .enumeration(let values): body = try enumeration(values, name: name, pointer: pointer)
            case .booleanConstant(let value): body = booleanLiteral(value, name: name)
            // swiftlint:disable:next pattern_matching_keywords
            case .object(let fields, let additional):
                try validateLayout(pointer, visiting: [])
                body = try record(fields, additional: additional, name: name)
            // swiftlint:disable:next pattern_matching_keywords
            case .union(let kind, let branches):
                body = try union(kind, branches: branches, name: name, pointer: pointer)
            default: throw graph.error(pointer, "Unsupported declaration")
            }
            let family =
                graph.swiftName.hasPrefix("Anthropic")
                ? "Anthropic" : graph.swiftName.hasPrefix("OpenAI") ? "OpenAI" : "Fixtures"
            let imported = graph.importModule.map { "import \($0)\n\n" } ?? ""
            let source =
                "// Generated by littleswitch-tools contracts. Do not edit.\n"
                + "// Source: \(comment(graph.rootID)) \(comment(pointer))\n"
                + graph.provenance.map { "// \(comment($0))\n" }.joined()
                + graph.projectionNotes.map { "// Projection: \(comment($0))\n" }.joined()
                + "\n" + imported + body + "\n"
            files.append(GeneratedContractFile(relativePath: family + "/" + name + ".swift", source: source))
        }
        guard !files.isEmpty else { throw graph.error(root.pointer, "A root must project to a record, enum, or union") }
        return files.sorted { $0.relativePath < $1.relativePath }
    }

    private func comment(_ value: String) -> String {
        value.components(separatedBy: .newlines).joined(separator: " ")
    }

    mutating func type(_ pointer: String, suggested: String) throws -> String {
        let node = try graph.resolved(pointer)
        let shape = try presence(pointer)
        let suggested = graph.typeNames[node.pointer] ?? suggested
        if shape.nullable, shape.base != node.pointer {
            return try type(shape.base, suggested: suggested) + "?"
        }
        switch node.kind {
        case .scalar(.string): return "String"
        case .scalar(.number): return "JSONNumber"
        case .scalar(.boolean): return "Bool"
        case .openEnum(let known): return "OpenWireValue<\(try type(known, suggested: suggested))>"
        case .opaque: return "JSONValue"
        case .array(let item): return "[\(try type(item, suggested: suggested + "Item"))]"
        case .null: throw graph.error(pointer, "Null-only values need an explicit projection")
        case .reference: throw graph.error(pointer, "Unresolved alias")
        case .object, .enumeration, .booleanConstant, .union:
            if let name = names[node.pointer] { return name }
            let name = ContractSwiftNames.type(graph.typeNames[node.pointer] ?? suggested)
            guard !names.values.contains(name),
                !["String", "Bool", "JSONNumber", "JSONValue", "JSONPresence", "WireObject", "Key"].contains(name)
            else {
                throw graph.error(pointer, "Swift type name collision: \(name)")
            }
            names[node.pointer] = name
            pending.append(node.pointer)
            return name
        }
    }

    func presence(_ pointer: String) throws -> (base: String, nullable: Bool) {
        let node = try graph.resolved(pointer)
        if case .opaque = node.kind { return (node.pointer, true) }
        // swiftlint:disable:next pattern_matching_keywords
        if case .union(let kind, let members) = node.kind {
            let nonnull = try members.filter { if case .null = try graph.resolved($0).kind { false } else { true } }
            let nullCount = members.count - nonnull.count
            if kind == .oneOf, nullCount > 0 {
                guard nullCount == 1, try nonnull.allSatisfy({ try excludesNull($0, visiting: []) }) else {
                    throw graph.error(node.pointer, "Ambiguous nullable oneOf requires an explicit projection")
                }
            }
            if nonnull.count == 1, nonnull.count < members.count { return (nonnull[0], true) }
        }
        return (node.pointer, false)
    }

    private func excludesNull(_ pointer: String, visiting: Set<String>) throws -> Bool {
        let node = try graph.resolved(pointer)
        guard !visiting.contains(node.pointer) else { return false }
        switch node.kind {
        case .null, .opaque: return false
        case .union(_, let members):
            return try members.allSatisfy { try excludesNull($0, visiting: visiting.union([node.pointer])) }
        case .reference: throw graph.error(pointer, "Unresolved alias")
        case .scalar, .enumeration, .booleanConstant, .openEnum, .object, .array: return true
        }
    }

    private func booleanLiteral(_ value: Bool, name: String) -> String {
        let literal = value ? "true" : "false"
        return """
            public enum \(name): CaseIterable, Equatable, Sendable, WireCodable {
                case value

                public init(wireJSON: JSONValue) throws {
                    guard try Bool(wireJSON: wireJSON) == \(literal) else {
                        throw WireCodingError(.invalidDiscriminator)
                    }
                    self = .value
                }

                public func wireJSON() -> JSONValue { .boolean(\(literal)) }
            }
            """
    }

    private func validateLayout(_ pointer: String, visiting: Set<String>) throws {
        let shape = try presence(pointer)
        let node = try graph.resolved(shape.base)
        guard case .object(let fields, _) = node.kind else { return }
        guard !visiting.contains(node.pointer) else {
            throw graph.error(pointer, "Recursive Swift value layout requires an array or indirect union")
        }
        for field in fields { try validateLayout(field.schema, visiting: visiting.union([node.pointer])) }
    }

    private func enumeration(_ values: [String], name: String, pointer: String) throws -> String {
        let cases = values.map(ContractSwiftNames.member)
        try ContractSwiftNames.unique(cases, contract: graph.rootID, pointer: pointer)
        let declarations = zip(cases, values).map { "    " + ContractSwiftNames.enumCase($0, value: $1) }
            .joined(separator: "\n")
        return """
            public enum \(name): String, CaseIterable, Sendable, WireCodable {
            \(declarations)

                public init(wireJSON: JSONValue) throws {
                    let rawValue = try String(wireJSON: wireJSON)
                    guard let value = Self(rawValue: rawValue) else {
                        throw WireCodingError(.invalidDiscriminator)
                    }
                    self = value
                }

                public func wireJSON() -> JSONValue { .string(rawValue) }
            }
            """
    }
}
